// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebapplikasjonSemesterOppgave.Areas.Identity.Data;

#nullable disable

namespace WebapplikasjonSemesterOppgave.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231010140715_ServiceOrder")]
    partial class ServiceOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebapplikasjonSemesterOppgave.Models.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerAgreement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModelYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReparationDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReplacedPartsReturned")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ServiceOrRepair")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ShippingMethods")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Warranty")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServiceOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
